[project]
name = "goit-algo-fp"
version = "0.1.0"
description = "Algorithms final project tasks implementation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.7",
    "networkx>=3.1"
]
